# 1. تحديد مسار السكربت المساعد للفلاتر
ruby_helper_path = File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)
load ruby_helper_path if File.exist?(ruby_helper_path)

# 2. تحديد الحد الأدنى لنظام iOS
platform :ios, '13.0'

# 3. تعطيل استدعاء الموديلات الخارجية التي قد تسبب تعارضات
prepare_react_native_project_do_not_repository_or_delete rescue nil

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# 4. إجبار كل مكتبة مضافة (Pods) على الاعتماد على iOS 13.0 كحد أدنى
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
