name: Build iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build-ipa:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Disable Swift Package Manager for iOS
      run: flutter config --no-swift-package-manager

    - name: Install Dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: |
        cd ios
        pod install --repo-update

    - name: Build iOS App
      run: flutter build ios --release --no-codesign

    - name: Create Unsigned IPA Package
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        mv Runner.app Payload/
        zip -r App.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-ipa
        path: build/ios/iphoneos/App.ipa
